# Site settings
baseurl = "https://vektorcr.tk"
languageCode = "es-us"
title = "Vektor Costa Rica"

[params]

    name = "Vektor Costa Rica"
    description = "Empresa de consultoria de salud ocupacional"

        # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "your@email.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Vektor Costa Rica"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Vektor Costa Rica"
        subtitle = "Capacitaciones - Certificaciones - Validación de Requerimientos"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Cursos"

        [params.portfolio.modal]
            client = "Cliente"
            date = "Fecha"
            category = "Categoria"
            buttontext = "Cerrar"


    [params.about]
        title = "Nosotros"
        # The about text is splitted into a left and right column
        left = "Visión: Lograr ser líderes en nuestra área para el año 2020, garantizando siempre la calidad y profesionalismo de nuestros servicios."
        right = "Misión: Nuestra misión es alcanzar su visión."

    [params.services]
        title = "Servicios"
        left = "Visión: Lograr ser líderes en nuestra área para el año 2020, garantizando siempre la calidad y profesionalismo de nuestros servicios."
        right = "Misión: Nuestra misión es alcanzar su visión."

    [params.team]
        title = "Nuestro equipo"
        left = "Visión: Lograr ser líderes en nuestra área para el año 2020, garantizando siempre la calidad y profesionalismo de nuestros servicios."
        right = "Misión: Nuestra misión es alcanzar su visión."
    
    [params.contact]
        title = "Contactenos"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Nombre"
            error = "Por favor introduzca su nombre"

        [params.contact.form.email]
            text = "Correo electrónico"
            error = "Por favor introduzca su correo electrónico"

        [params.contact.form.phone]
            text = "Teléfono"
            error = "Por favor introduzca su número teléfonico"

        [params.contact.form.message]
            text = "Mensaje"
            error = "Por favor introduzca un mensaje"

        [params.contact.form.button]
            text = "Enviar"


    [params.footer]
        copyright = "© TODOS LOS DERECHOS RESERVADOS"

        contactInformation = "info@vektorcr.com. Tel: 4001-6915 / 7112-9590"

        [params.footer.location]
            title = "Vektor Costa Rica"
            # Postal address (add as many lines as necessary)
            address = ["Juntos hacía el éxito"]

        [params.footer.social]
            title = "Redes Sociales"
            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link = "//www.facebook.com/Vektor-Safety-2042099979401870/"

            [[params.footer.social.networks]]
                icon = "fa-youtube"
                link=  "https://www.youtube.com/channel/UC0UBddXUX5tuTlFPVsdwPlg"


        [params.footer.credits]
            title = ""
            image = "cfiaBlanco1.jpg"
            text = "Inscripción: CC-08948"
